### ISSUE TITLE
Add flatMap operator

### ISSUE THREAD

**Issue by Roh-codeur** [biaslab/Rocket.jl#11]
Hi

Thanks for putting this together, looks like an awesome library

I have an array of values. for each value, I download relevant data from a website. this creates a data frame with m cols and n rows. for a particular column, each row corresponds to a URL, which I then intend to download and then merge data for all n rows
1. is there a way to do a FlatMap, so, I can read each column, now asynchronously download files for each row.
2. How do I then merge data from these files into a data frame? 

Thanks
Rohit

```
using Rocket

function downloadDataForMarket(market::String, forceDownload::Bool)
@info "downloadDataForMarket market: $market thread: $(Threads.threadid())"
df = DataFrame(A = rand(Int, 2), B = rand(Int, 2))
return df.A
end

function downloadDataForTicker(market, ticker)
@info "downloadDataForTicker thread: $(Threads.threadid())"
return market
end

markets = ["NSE", "US"]
exchanges = ["NSE", "NYSE"]

marketsSource = from(markets, scheduler = AsyncScheduler())

subscribe!(
marketsSource |>
map(Vector{Int64}, (d) -> downloadDataForMarket(d, true)) |>
map(Vector{Int64}, (d) -> downloadDataForTicker(d, true)) |>
map(Vector{Int64}, (d) -> d), logger())

```

**Comment by bvdmitri** [comment]
Hi!

You are probably looking for [`merge_map`](https://biaslab.github.io/Rocket.jl/stable/operators/transformation/merge_map/) operator. Different libraries has different naming conventions and at least `merge_map` should be an equivalent to [`flatMap`](http://reactivex.io/documentation/operators/flatmap.html) operator from ReactiveX. Note that `merge_map` merges emissions so that they may interleave and may not come in the same order as in the initial array. If you want to preserve an order you may look into [`concat_map`](https://biaslab.github.io/Rocket.jl/stable/operators/transformation/concat_map/).

Regarding your question about merging your data into data frame it would be better to refer to the [DataFrames.jl documentation](https://dataframes.juliadata.org/stable/).

**Comment by Roh-codeur** [comment]
@bvdmitri : thanks, that worked!
