### ISSUE TITLE
Documentation references non-existent function `func`

### ISSUE THREAD

**Issue by caleb-allen** [biaslab/Rocket.jl#19]
The documentation refers to a function `func` which does not exist.

https://github.com/biaslab/Rocket.jl/blame/master/docs/src/observables/about.md#L124

I would submit a correction but I don't know the correct way to get a value from an observable synchronously.

**Comment by bvdmitri** [comment]
Hey @caleb-allen ! `func` is just an arbitrary name for a function, it can be any name, this section describes the difference between functions and observables. There is nothing to correct, because in reactive paradigm in general there is no way to
>  get a value from an observable synchronously.
It is only possible to subscribe to new values in observables, in contrast to a function.
However I agree that documentation could be improved and we can be more clear about it in this example.

**Comment by bvdmitri** [comment]
@caleb-allen I made a PR #20 with documentation fix  , you can check it out and say if its more clear now.

**Comment by caleb-allen** [comment]
Ah, I understand, thanks for the clarification! My misunderstanding. Your changes in #20 are much more clear, thank you!

Great library, btw!
