### ISSUE TITLE
Confusing output order

### ISSUE THREAD

**Issue by zsoerenm** [biaslab/Rocket.jl#34]
Consider this MWE:

```julia
using Rocket

inputS = RecentSubject(Float64)

verified_inputS = inputS |> map(Float64, x -> x < 0 ? -x : x)

subscribe!(verified_inputS, verified_input -> begin
    if (inputS.recent != verified_input)
        next!(inputS, verified_input)
    end
end
)

subscribe!(inputS, logger())

next!(inputS, -1.0)
```

Which outputs

```
[LogActor] Data: 1.0
[LogActor] Data: -1.0
```

However, I would have expected

```
[LogActor] Data: -1.0
[LogActor] Data: 1.0
```

Because `next!(inputS, -1.0)` is called before `next!(inputS, verified_input)`

I need to implement a little "hack" with `@async` to get the expected order:

```julia
subscribe!(verified_inputS, verified_input -> begin
    if (inputS.recent != verified_input)
        @async next!(inputS, verified_input)
    end
end
)
```

**Comment by bvdmitri** [comment]
The order, while being confusing, is correct. 
The calling order does not really matter, but the completion order (because the events can be delayed or entirely ignored for various reasons).
You call `next!(inputS, -1.0)` which does call `next!(inputS, 1.0)` under the hood, hence `next!(inputS, 1.0)` completes **before** `next!(inputS, -1.0)`. 
This is why `@async` trick helps you because it explicitly delays the inner `next!(inputS, 1.0)` until the `next!(inputS, -1.0)` completes.

Such situations where your observable depends on itself are dangerous and might be confusing indeed, but I don't think the current behaviour here is incorrect.
