### ISSUE TITLE
Asynchronous execution question

### ISSUE THREAD

**Issue by caxelrud** [biaslab/Rocket.jl#6]
Hi,
I am looking for to translate Python code that uses RxPY in Jupyter Notebooks.
It works very well. Using _interval_ function, It allows cells to execute periodically and display its results.
The executions are asynchronous and they don't block the Jupyter Notebook.
How can I do the same async execution using Rocket.jl? 
Thanks.

Relevant code in Python:
```
from rx.concurrency import ThreadPoolScheduler
from rx import Observable

threadpool_scheduler = ThreadPoolScheduler()
observable1 = Observable.interval(15000).observe_on(threadpool_scheduler)
subscription = observable1.subscribe(
         lambda value: specialPrint(out1,"\rRunningThread:{}, Value:{},\t DateTime:{}".\
                     format(threading.get_ident(),value, datetime.datetime.now())),
         lambda error: specialPrint(out1,"\rRunningThread:{}, Error:{}, \t DateTime:({})".\
                     format(threading.get_ident(),error, datetime.datetime.now())),
         lambda: specialPrint(out1,"\rRunningThread:{}, Complete!, \t DateTime:({})".\
                     format(threading.get_ident(),datetime.datetime.now())))
```

**Comment by bvdmitri** [comment]
Hi!

`interval` function in Rocket.jl by default uses asynchronous execution with built-in Julia `Task` object and won't block Jupyter notebook. The relevant code in Julia with Rocket.jl would be something like:

```
observable = interval(1000)

subscription = subscribe!(observable, lambda(
    on_next = (d) -> println("Data: ", d),
    on_error = (e) -> println("Error", e),
    on_complete = () -> println("Completed")
))

# dont forget to unsubscribe
# unsubscribe!(subscription)
```

Since Julia is single-threaded programming language this piece of code will run on a single CPU. 

If you really want to execute your observable on a different threads you can also try to use experimental `ThreadsScheduler`  object with `schedule_on` operator (see docs). 
```
observable = interval(1000) |> schedule_on(Rocket.ThreadsScheduler())
```
This functionality is experimental. You should also start julia with a custom  number of threads: [link](https://discourse.julialang.org/t/how-to-change-the-number-of-threads/6169)

For more examples see the [documentation](https://biaslab.github.io/Rocket.jl/stable/)
